target 'PaytmMobileChallenge' do
    use_frameworks!
    
    pod 'BrightFutures'
    pod 'couchbase-lite-ios'
    
    target 'PaytmMobileChallengeTests' do
        inherit! :search_paths
        
        pod 'BrightFutures'
    end
end
