
typealias ExchangeRate = [String: Any]

enum ExchangeAbbreviation: String {
    case australianDollar = "AUD"
    case bulgarianLev = "BGN"
    case brazilianReal = "BRL"
    case canadianDollar = "CAD"
    case switzerlandFranc = "CHF"
    case chineseYuan = "CNY"
    case czechKoruna = "CZK"
    case denmarkKrone = "DKK"
    case greatBritainPound	= "GBP"
    case hongKongDollar = "HKD"
    case croatiaKuna = "HRK"
    case hungaryForint = "HUF"
    case indonesiaRupiah = "IDR"
    case israelNewShekel = "ILS"
    case indiaRupee = "INR"
    case japanYen = "JPY"
    case southKoreaWon = "KRW"
    case mexicoPeso = "MXN"
    case malaysiaRinggit = "MYR"
    case norwayKroner = "NOK"
    case newZealandDollar = "NZD"
    case philippinesPeso = "PHP"
    case polandZloty = "PLN"
    case romaniaNewLei = "RON"
    case russiaRouble = "RUB"
    case swedenKrona = "SEK"
    case singaporeDollar = "SGD"
    case thailandBaht = "THB"
    case turkishNewLira = "TRY"
    case unitedStatesDollar = "USD"
    case southAfricaRand = "ZAR"
    case euro = "EUR"
}
